language: scala #or java => to trigger the build on a 'jvm-otp' box
env:
  - PLAY_VERSION=2.0
  - PLAY_VERSION=2.0.1
before_script: ./travis/setup
script: ./travis/play-framework/play test
notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email: false
